version: "3.3"

services:
  web:
    build: ./DockerTest
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./DockerTest/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=docker_test
      - POSTGRES_PASSWORD=docker_test
      - POSTGRES_DB=docker_test
      
volumes:
  postgres_data:
